### ISSUE TITLE
Difference between episode_way and low_way

### ISSUE THREAD

**Issue by InugYoon** [icoz69/CEC-CVPR2021#9]
Hello, first of all thank you sharing great project.
During understanding the code, I got some questions about the details.

First is about the difference between episode_way<>low_way and episode_shot<>query_shot
I thought it is way, shot used for PIL algorithm on the session 0 training in cec/fscil_trainer.
Is it correct that episode_way/shot is for extracting (Sb,Qb) and low_way/shot is for (Si,Qi) on algorithm 1?
If it is right, is there any meaning for making difference on them? On the example training arguments that is written on Readme, all episode_way=low_way and episode_shot=low_shot. 

Thank you for reading

**Comment by Nan-S** [comment]
Thanks for your questions, your understanding is correct. We made different names on them to do the experiments on using different ways/shots for pseudo base and pseudo incremental. We found that episode_way=low_way and episode_shot=low_shot is the best choice, that's why in Readme they are all equal.

**Comment by InugYoon** [comment]
Wow, thank you for your clear answer. 
Thanks!!
